version: '3'
services:
  app:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_HOST=host"
      - "DB_PORT=3306"
      - "DB_DATABASE=database"
      - "DB_USERNAME=user"
      - "DB_PASSWORD=password"
    depends_on:
      - dbeducajud
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    container_name: db
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
